# Generated by Django 3.1 on 2020-08-14 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'ordering': ('-created_at',), 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.RemoveField(
            model_name='field',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='field',
            name='content',
        ),
        migrations.RemoveField(
            model_name='field',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='slug',
        ),
        migrations.AddField(
            model_name='field',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Short answer'), ('textarea', 'Paragraph'), ('radio', 'Multiple choice'), ('checkbox', 'Checkboxes'), ('select', 'Dropdown'), ('date', 'Date')], default=1, max_length=100, verbose_name='Answer type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='core.forms'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forms',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ResponseQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1001, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.response')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.forms'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.field')),
            ],
        ),
    ]
