# Generated by Django 3.1 on 2020-08-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(default=1, max_length=50, verbose_name='full_name'),
            preserve_default=False,
        ),
    ]
