# Generated by Django 3.1 on 2020-08-12 09:45

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200812_1333'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', accounts.models.MyUserManager()),
            ],
        ),
    ]
