# Generated by Django 3.1 on 2020-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200812_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
    ]
