# Generated by Django 3.1 on 2020-08-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200812_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='phone'),
        ),
    ]
