# Generated by Django 3.1 on 2020-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200812_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='full name'),
        ),
    ]
