# Generated by Django 3.1 on 2020-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200812_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
